<a href="https://colab.research.google.com/github/GretRincon/PrimerProyectoFisica/blob/master/SeriePythonBasico_G.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Serie Python 
### Temas básicos de python.

Las indicaciones son editar este archivo, deje casillas de código para que sea de la manera más ordenada posible, una vez que estén sus funciones deben subir a classroom el ipynb y generar un pdf de el mismo. 

**TODAS LAS CASILLLAS DEBEN ESTAR EJECUTADAS**

Muchos incisos implican inputs del usuario, ustedes deben probar cada una de sus funciones (ingresar los valores que se pidan) para mandarme el archivo ipynb y el pdf una vez que hayan ejecutado todo para que vea los outputs de sus programas. En caso de que no lo hagan de esa manera y lo manden sin ejecutar tendrán un **punto menos** en la serie.



Mi recomendación personal es que una vez que tengan su serie lista reinicien el kernel y ejecuten todo así podrán probar que todo este correcto antes de enviarlo.


No considero que sea una serie dificil, el fin es sólo que práctiquen. Hay muchas cosas que pueden hacerse en una línea si investigan sobre funciones que ya están implementadas en python. 

Si lo hacen de ambas maneras tendrán un punto extra y si comentan todo su código pueden tener otro punto extra.


Cualquier duda o complicación comuniquense conmigo.


Saludos.

In [24]:
print("EJEMPLO:")
input("Está casilla ha sido ejecutada por: ")


EJEMPLO:
Está casilla ha sido ejecutada por: Gretchen


'Gretchen'

1) Crea una lista que regrese los multiplos de 7 y números que lleven algún siete en sus cifra hasta el 700. 

    [Out]: [7, 14, 17, 21, 27, 28, 35, 37, ...]

In [8]:
print("Solo se admiten números múltiplos de 7 y con un 7, entre 7 y 700")
#hasta 700, multiplos de 7 & con 7
num=0 
lista=[]
for num in range (701):
  if num%7==0:
   carc=str(num)
   for i in range (0,len(carc)):
    if carc[i]=="7":
         lista.append(num)
   
print(lista)
  
  


Solo se admiten números múltiplos de 7 y con un 7, entre 7 y 700
[7, 70, 77, 77, 147, 175, 217, 273, 287, 357, 371, 378, 427, 476, 497, 567, 574, 637, 672, 679, 700]


2) Realiza una función que reciba un número y regrese dicho número elevado por un número aleatorio entero entre el 1 y el 10

In [0]:
from random import randint
a=int(input("Escriba un número "))
#solo potencias aleatorias de 0 a 10
b=randint(0,10)
salida=pow(a,b)
print("Su numero será elevado al numero",b," obtenido aleatoriamente")
print(salida)

3) Crea una función que reciba dos números e indique si son múltiplos el uno del otro 

In [12]:
a=int(input("Ingrese un número entero "))
b=int(input("Ingrese otro número entero "))
c=0

#ninguno es multiplo 
if b%a==0 or a%b ==0:
    print("Tienes un número múltiplo de otro")
else:
   print("Tus números no son multiplos")
       

 

Ingrese un número entero 3
Ingrese otro número entero 3
Tienes un número múltiplo de otro


4) Crea una función que reciba una lista desordenada de números y la ordene de mayor a menor

    Ejemplo: [In]: [77, 1, 364, 587, 21, 13, 54, 999]  [Out]: [999, 587, 364, 77, 54, 21, 13, 1]

In [214]:

lista=[]
for a in range (10):
    lista.append(int(input("Ingrese un número ")))
print("Su lista es: ", lista)
lista.sort(reverse=False) #ordenar lista
print("Su lista ordenada es: ", lista)
#usar sort sirve para el primer digito(alfabetico), a menos que conviertas en integer



Ingrese un número 4
Ingrese un número 5
Ingrese un número 6
Ingrese un número 2
Ingrese un número 8
Ingrese un número 0
Ingrese un número 44
Ingrese un número 77
Ingrese un número 7
Ingrese un número 55
Su lista es:  [4, 5, 6, 2, 8, 0, 44, 77, 7, 55]
Su lista ordenada es:  [0, 2, 4, 5, 6, 7, 8, 44, 55, 77]


5) Teniendose una lista con números entre el uno y el diez que pueden o no estar repetidos realiza un programa que pueda regresar el número que no está repetido de cualquier lista de este tipo.

    Ejemplo: [In]: [ 1, 1, 2, 2, 3, 4, 4, 5, 5, 6, 6, 7, 7]  [Out]: 3

In [18]:
from random import randint
lista=[]
irrep=[]
#crear lista aleatoria
for cont in range (10):
  lista.append(randint(1,10))
print(lista)

#si el numero n aparece solo una vez en la lista, anotala en los irrepetibles
for n in lista:
 #numero de veces que aparece n
  if lista.count(n)==1: 
    irrep.append(n)

print(irrep)


[5, 4, 9, 2, 10, 6, 3, 4, 7, 3]
[5, 9, 2, 10, 6, 7]


6) Implementa una función que reciba una lista de números enteros entre el uno y el diez que pueden o no estar repetidos y regrese un diccionario cuya clave sea el número (de menor a mayor) y el valor el número de veces que se repite ese item en la lista.

      Ejemplo: [In]:[1, 8, 9, 6, 4, 1, 1, 5, 4, 2, 3, 5, 5, 8, 1, 3, 2] 
               [Out]: { 1:4 , 2:2 , 3:2, 4:2, 5:3, 6:1, 8:2, 9:1} 

**NOTA**: Consideren que la lista sólo va de 1 al 10 así que pueden evaluar primero los valores dentro de la lista o evaluar del 1 al 10 con lo que obtendrían: { 1:4 , 2:2 , 3:2, 4:2, 5:3, 6:1, 7:0, 8:2, 9:1, 10:0 }

In [81]:
#Para no recibir tantos numeros los genero aleatoriamente
from random import randint
lista=[]
diccionario={}
for cont in range (1,10):
  lista.append(randint(1,10))
print("lista original",lista)
for cont in range (1,10):
  diccionario.update({cont:lista.count(cont)})
print("diccionario, num: veces escrito en la lista ",diccionario) 

lista original [6, 6, 7, 1, 5, 8, 7, 6, 3]
diccionario, num: veces escrito en la lista  {1: 1, 2: 0, 3: 1, 4: 0, 5: 1, 6: 3, 7: 2, 8: 1, 9: 0}


7) Elabora una función que reciba valores del usuario y los añada a una lista con la condición de que sea un valor númerico entre el 0 y 10.  

**OPCIONAL +1 punto en la serie**: En caso de que no sea un valor númerico que levante <raise> una excepción creada por ustedes que se llamen "aquí no"

In [227]:
lista=[]
x='no'
for x in range (5): #solo puede poner 5
 x=float(input("Ingresa un número, solo entre 0 y 10 "))
 if x <= 10:
     if x >= 0:
       lista.append(x)
print(lista)
#Puede mejorar

Ingresa un número, solo entre 0 y 10 1
Ingresa un número, solo entre 0 y 10 345
Ingresa un número, solo entre 0 y 10 3
Ingresa un número, solo entre 0 y 10 5
Ingresa un número, solo entre 0 y 10 6
[1.0, 3.0, 5.0, 6.0]


8) Haz una función que reciba una frase y regrese un booleano True en caso de ser palindromo y False de no serlo.

    Ejemplo: [In]: "Anita lava la tina"  [Out]: True
    
**NOTA**: Tomen en cuenta que los espacios no deben ser tomados en cuenta y que Python es sensible a mayúsculas y minúsculas.

In [53]:

def palindromo(cadena):
  minusculas=cadena.lower() #A minusculas
  cont=0
  listareves=[]
  minesp=minusculas.replace(" ","")
  print(minesp) #imprimes original sin espacio y en minusculas
  listareves=minesp[::-1] #orden al reves
  print(listareves) #imprimes al reves, listo para ver si es palindromo
  return listareves==minesp

cadena=(input("Ingresa un palindromo "))
print(palindromo(cadena))



Ingresa un palindromo ANita lava la tina
anitalavalatina
anitalavalatina
True


9) Escribe una función que reciba una cadena y regrese un diccionario donde la llave sea la vocal y el valor el número de veces que aparece en dicha cadena. 

    Ejemplo: [In]: "Parangaricutirimicuaro"   [Out]: { 'a':4, 'e':0, 'i':4, 'o':1, 'u':2 }

In [70]:
def Vocales(cadena):
  
  Dicc={}
  cadena=cadena.lower()
  for vocal in ['a','e','i','o','u']:
    Dicc.update({vocal:cadena.count(vocal)})
  return Dicc
frase=str(input("Ingrese una frase o palabra: "))
print(Vocales(frase))

Ingrese una frase o palabra: Abecedario
{'a': 2, 'e': 2, 'i': 1, 'o': 1, 'u': 0}


8) Realiza una función que al ingresar tu altura y tu peso regrese tu índice de masa corporal(IMC)
    
**NOTA**: IMC= peso en kg / estatura en metros al cuadrado

In [110]:
alt=float(input("Ingresa tu altura en metros "))
peso=float(input("Ingresa tu peso en kg "))
IMC=peso/(alt**2)
print(IMC)

Ingresa tu altura en metros 1.5
Ingresa tu peso en kg 55
24.444444444444443


9) Elabora un programa que permita realizar la suma de dos matrices 3x3. Los datos de ambas matrices deberán ser ingresados por el usuario.

**NOTA** : Las matrices en python puede implementarse con listas dentro de listas

In [186]:

matriz1=[[0,0,0],[0,0,0],[0,0,0]] 
matriz2=[[0,0,0],[0,0,0],[0,0,0]] 
matrizsuma=[[0,0,0],[0,0,0],[0,0,0]] 
print("Ingrese una matriz de 3x3")
for contf in range (3):
  for contc in range (3):
    print("Ingrese el valor",contf,contc)
    matriz1[contf][contc]=float(input("Aqui "))
print("Ingrese una segunda matriz de 3x3")
for contf in range (3):
  for contc in range (3):
    print("Ingrese el valor", contf, contc)
    matriz2[contf][contc]=float(input("Aqui "))
for contf in range (3):
  for contc in range (3):
      matrizsuma[contf][contc]=matriz1[contf][contc]+matriz2[contf][contc]

print(matrizsuma)

Ingrese una matriz de 3x3
Ingrese el valor 0 0
Aqui 1
Ingrese el valor 0 1
Aqui 1
Aqui 1
Ingrese el valor 0 2
Ingrese el valor 1 0
Aqui 1
Ingrese el valor 1 1
Aqui 1
Ingrese el valor 1 2
Aqui 1
Ingrese el valor 2 0
Aqui 1
Ingrese el valor 2 1
Aqui 1
Ingrese el valor 2 2
Aqui 1
Ingrese una segunda matriz de 3x3
Ingrese el valor 0 0
Aqui 2
Ingrese el valor 0 1
Aqui 2
Ingrese el valor 0 2
Aqui 2
Ingrese el valor 1 0
Aqui 2
Ingrese el valor 1 1
Aqui 2
Ingrese el valor 1 2
Aqui 2
Ingrese el valor 2 0
Aqui 2
Ingrese el valor 2 1
Aqui 2
Ingrese el valor 2 2
Aqui 2
[[3.0, 3.0, 3.0], [3.0, 3.0, 3.0], [3.0, 3.0, 3.0]]


10) Con ayuda de las sentencias if y elif elabora una calculadora que permita sumar, restar, multiplicar y dividir dos números. El usuario podrá elegir qué operación desea realizar e ingresar dichos dos números.

In [80]:
op=input("Escriba que operación quiere efectuar sobre dos números: suma, resta, mult, div ")
a=float(input("Escriba el primer número "))
b=float(input("Escriba el segundo número "))
if op=='suma':
  print(a," + ",b," = ",a+b)
elif op=='resta':
  print(a," - ",b," = ",a-b)
elif op=='mult':
  print(a," * ",b," = ",a*b)
elif op=='div':
  print(a," * ",b," = ",a/b)

Escriba que operación quiere efectuar sobre dos números: suma, resta, mult, divsuma
Escriba el primer número1
Escriba el segundo número44
1.0  +  44.0  =  45.0


11) Implementando funciones lamba, elabora un programa que permita realizar las operaciones básicas aritméticas

In [83]:
a=float(input("Escriba el primer número "))
b=float(input("Escriba el segundo número "))
op=input("Escriba que operación quiere efectuar sobre dos números: suma, resta, mult, div ")
if op=='suma':
  x=lambda a,b:a+b
  print(x(a,b))
elif op=='resta':
  y=lambda a,b:a-b
  print(y(a,b))
elif op=='mult':
  z=lambda a,b:a*b
  print(z(a,b))
elif op=='div':
  w=lambda a,b:a/b
  print(w(a,b))

Escriba el primer número 1
Escriba el segundo número 33
Escriba que operación quiere efectuar sobre dos números: suma, resta, mult, div suma
34.0


12) Haz una función que regrese los números primos menores de 50

    Ejemplo: [Out]: [ 1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 47]

In [98]:
lista=[]
ant=1
cont=0
for num in range (2,50):
  for ant in range (2,num-1):
    if num%ant==0:
      break
  else:
      lista.append(num)
print(lista)


[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


13) Realiza una función donde ingreses un número "n" y que regrese "n" términos de la serie fibonacci
    
    Ejemplo: [In]: 11 [Out]: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55 ]

In [113]:
def fibonacci(n):
 f0=0
 f1=1
 fibo=[0,1]
 for cont in range (2,n):
  fibo.append(fibo[cont-1]+fibo[cont-2])
 return fibo

n=int(input("Te mostrare la serie de fibonacci, hasta una iteración n. ¿Que n quieres elegir? "))
print(fibonacci(n))

Te mostrare la serie de fibonacci, hasta una iteración n. ¿Que n quieres elegir? 7
[0, 1, 1, 2, 3, 5, 8]


14) Escribe una función que pida un número "n" y luego pida al usuario "n" número de entradas

In [133]:
def entradas():
  lista=[]
  n=int(input("Ingrese el número de entradas que desea "))
  for cont in range (1,n+1):
    lista.append(input("Ingrese un valor "))
entradas()

Ingrese el número de entradas que desea 3
Ingrese un valor 234
Ingrese un valor 2
Ingrese un valor 456


15) Realiza una función que reciba una matriz 3x3 y regresé la transpuesta de dicha matriz

In [202]:
import numpy as np
A=np.array([[1,23,100],[2,3,4],[-1,-2,-3]])
print("Matriz original")
print(A)
def transp(matriz):
  zirtram=np.linalg.inv(matriz) #Jaja ya se que esta funcion en realidad solo la importe, pero da flojera
  return zirtram
print("Matriz transpuesta")
print(transp(A))



Matriz original
[[  1  23 100]
 [  2   3   4]
 [ -1  -2  -3]]
Matriz transpuesta
[[ 0.01818182  2.38181818  3.78181818]
 [-0.03636364 -1.76363636 -3.56363636]
 [ 0.01818182  0.38181818  0.78181818]]


16) Crea una lista con los números del 1 al 100 que en los multiplos de 7 y números que lleven algún siete en sus cifra regrese la cadena "Aplauso"

    Ejemplo: [Out]: [1, 2, 3, 4, 5, 6, "Aplauso", 8, 9, 10, 11, 12, 13, "Aplauso", 15, 16, "Aplauso", 18, 19, 20, "Aplauso", 22, 23, 24, 25, 26,"Aplauso", "Aplauso", 29, 30, 31, 32, 33, 34, "Aplauso", 36, "Aplauso", 38, 39, 40, 41, "Aplauso", 43, 44, 45, 46, "Aplauso", 48, "Aplauso", 50, 51, 52, 53, 54, 55, "Aplauso", "Aplauso", 58, 59, 60, 61, 62, "Aplauso", 64, 65, 66, "Aplauso", 68, 69, "Aplauso", "Aplauso", "Aplauso", "Aplauso", "Aplauso", "Aplauso", "Aplauso", "Aplauso", "Aplauso", "Aplauso", 80, 81, 82, 83, "Aplauso", 85, 86, "Aplauso", 88, 89, 90, "Aplauso", 92, 93, 94, 95, 96, "Aplauso", "Aplauso", 99, 100]

In [142]:
#hasta 100, si el número es multiplos de 7 o con 7 se imprimira aplauso
num=0 
lista=[]
for num in range (1,101):
  carc=str(num)
  if num%7==0 or '7' in str(num):
    lista.append("Aplauso")
  else:
    lista.append(num)
   
print(lista)

[1, 2, 3, 4, 5, 6, 'Aplauso', 8, 9, 10, 11, 12, 13, 'Aplauso', 15, 16, 'Aplauso', 18, 19, 20, 'Aplauso', 22, 23, 24, 25, 26, 'Aplauso', 'Aplauso', 29, 30, 31, 32, 33, 34, 'Aplauso', 36, 'Aplauso', 38, 39, 40, 41, 'Aplauso', 43, 44, 45, 46, 'Aplauso', 48, 'Aplauso', 50, 51, 52, 53, 54, 55, 'Aplauso', 'Aplauso', 58, 59, 60, 61, 62, 'Aplauso', 64, 65, 66, 'Aplauso', 68, 69, 'Aplauso', 'Aplauso', 'Aplauso', 'Aplauso', 'Aplauso', 'Aplauso', 'Aplauso', 'Aplauso', 'Aplauso', 'Aplauso', 80, 81, 82, 83, 'Aplauso', 85, 86, 'Aplauso', 88, 89, 90, 'Aplauso', 92, 93, 94, 95, 96, 'Aplauso', 'Aplauso', 99, 100]


17) Haz una función que reciba un número "n" pueda crear una lista del 1 al 100 que regrese la cadena "NO" para los números divisibles entre el número "n"

    Ejemplo: [In]: 15 [Out]: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, "NO" , 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, "NO", 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, "NO", 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, "NO", 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, "NO", 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, "NO", 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]

In [149]:

def multno(n):
  lista=[]
  for cont in range (1,101):
    if cont%n==0:
      lista.append('NO')
    else:
      lista.append(cont)
  return lista
n=float(input("Ingrese un número del 1 al 100 "))
print(multno(n))

Ingrese un número del 1 al 100 10
[1, 2, 3, 4, 5, 6, 7, 8, 9, 'NO', 11, 12, 13, 14, 15, 16, 17, 18, 19, 'NO', 21, 22, 23, 24, 25, 26, 27, 28, 29, 'NO', 31, 32, 33, 34, 35, 36, 37, 38, 39, 'NO', 41, 42, 43, 44, 45, 46, 47, 48, 49, 'NO', 51, 52, 53, 54, 55, 56, 57, 58, 59, 'NO', 61, 62, 63, 64, 65, 66, 67, 68, 69, 'NO', 71, 72, 73, 74, 75, 76, 77, 78, 79, 'NO', 81, 82, 83, 84, 85, 86, 87, 88, 89, 'NO', 91, 92, 93, 94, 95, 96, 97, 98, 99, 'NO']


18) Dada una lista con elementos númericos del 1 al 100 elabora una lista por comprensión que guarde los elementos que son múltiplos de 5.

In [151]:
lista5=[]
lista5=[ i for i in range (2,101) if i%5==0 ]
print(lista5)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]


19) Escribe una función que tome un entero positivo "n" y regrese la suma de los cuadrados de todos los números pares menores o iguales que "n"

    Ejemplo: [In]: 12 [Out]: 364
    

In [161]:
def sumaparmenor(n): #n numero hasta el cual buscas cuadrados
#para cada elemento sumas i**2+... con i par & i<=n  
 suma=0
 for i in range (1,n+1):
   if i<=n and i%2==0:
     suma=suma+(i**2)
 return suma
n=int(input("Ingrese un entero positivo "))
print("Le devuelvo la suma de los cuadrados de los números pares menor o iguales que n: ",sumaparmenor(n))



Ingrese un entero positivo 12
Le devuelvo la suma de los cuadrados de los números pares menor o iguales que n:  364


19) Realiza una función que pida un número "n" y elabora un menú donde el usuario pueda elegir si quiere convertir  n a base binaria, hexadecimal u octal.

    Ejemplo suponiendo que se elige hexadecimal: [In]: 365 [Out]: 16d
    
**NOTA**: Pueden realizar la función desde 0 lo cuál les daría su punto extra o investiguen los métodos hex(), bin(),....

In [176]:
import sys
def conver():
  n=(int(input("Ingrese un número entero ")))
  print("¿A que base quiere convertir su número? Binaria, hexadecimal u octal ")
  print("Menu") 
  print("1)Binaria")
  print("2)Octal")
  print("3)Hexadecimal")
  
  base=input("Escribe el número deseado: ")
  if base=='1':
    resp=bin(n)
  elif base=='3':
    resp=hex(n)
  elif base=='2':
    resp=oct(n)
  
  return resp
  
print(conver())


Ingrese un número entero 3455
¿A que base quiere convertir su número? Binaria, hexadecimal u octal 
Menu
1)Binaria
2)Octal
3)Hexadecimal
Escribe el número deseado: 3
0xd7f


![texto alternativo](20) En esta opción eres libre de poner cualquier función. Debes comentar que es lo que hace

**NOTA**: No, no puede ser sólo un print. 

**NOTA**: No, tampoco cuenta hacer dos o tres prints. 

**NOTA**: Deben usar aunque sea un bucle, sean creativos. 

In [213]:
m=5
def term(n,m):
  
  lista=[n**k for k in range (5)]
  return lista

n=float(input(print("En la serie geometrica r^k, dale un valor a r y te digo si converge")))
if n<=abs(1):
  print("La seríe geometrica con ", n, "como k, converge")
else:
  print("¿Cómo va converger eso? Demuestralo")
print("Te regalo los primeros 5 términos de tu sucesión")
print(term(n,m))

En la serie geometrica r^k, dale un valor a r y te digo si converge
3
¿Cómo va converger eso? Demuestralo
Te regalo los primeros 5 términos de tu sucesión
[1.0, 3.0, 9.0, 27.0, 81.0]
